### ISSUE TITLE
Investigate backend solution for Sendgrid

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/Issues#10]

**Comment by LecCory** [comment]
Tested Azure send email service and it works great, and can be called programmatically and could be implemented as an Az function app endpoint. The caveat with this service is that it's currently in preview, so its not fully supported managed service and it's only available in US region. This means any data at rest would remain in US data centers. 

SendGrid is a 3rd party subscription service to Azure, provided by Twilio that I don't think will meet our needs, so I haven't invested more time into that option. 

With that being said, I'm currently investigating Az' managed SMTP services and nodemailer as a library that can be integrated with function apps.
