### ISSUE TITLE
e2e testing - Headless-recorder to emit bdd statements

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/Issues#12]

**Comment by vid** [comment]
Creating and updating any kind of test can be a lot of work. The headless recorder approach, using a browser extension, can save quite a bit of time and make it more practical to include a large number of related tests.
[x] identify work to base the recorder on
[x] test case to verify its code statements can be adapted to BDD type
[x] isolate the required functionality

[An open source Checkly extension](https://github.com/checkly/headless-recorder) is being used as a base. However, it includes a broad ecosystem of build and front end tools, which is deemed not suitable for an extension that records user input. So the following tasks are required:
[x] reduce the codebase in a new repository to the minimum required
[x] use Typescript for added type safety
[x] change to manifest v3 from manifest v2 for added security and longetivity
[x] create test cases for the included code
[x] move the majority of logic to a service, but make sure ui triggers from the extension are required for any capturing activities

**Comment by vid** [comment]
still to do; add page changes, remove unused code, package with commit testing.

**Comment by vid** [comment]
Ready for pipeline testing. Having some issues with on-commit tests being run for the repo itself.
