### ISSUE TITLE
Frontend app project folder structure

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/Issues#15]
Look into angular bundling.

**Comment by doug0102** [comment]
Some articles I've found so far. Next step is to create a mock application with a load of empty directives that bulk up the project. Test out some of the techniques listed below as well as how it effects bundling/size.
- [Angular: Core and Shared Modules](https://medium.com/@joao.aguas/angular-core-and-shared-modules-efe072bc9645)
- [Scalable Angular Structure](https://blog.adnanhalilovic.com/2022/07/18/scalable-angular-structure/)
- [High scalable folder structure in angular applications](https://medium.com/edataconsulting/high-scalable-folder-structure-in-angular-applications-a50b55f94350)
