### ISSUE TITLE
Figure out a good way to run cronjob style tasks in more managed infrastructure

### ISSUE THREAD

**Issue by Phanoix** [gctools-outilsgc/Issues#26]
This is trivial in a VM or kubernetes but not necessarily so in the world of azure web apps, etc.

**Comment by LecCory** [comment]
You could have a timed trigger run a function that calls a stored procedure in Maria/MySQL 

https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?pivots=programming-language-javascript&tabs=python-v2%2Cin-process

**Comment by Phanoix** [comment]
Outside of a db backup, most don't hit the DB but otherwise agreed, timed functions are probably the way to do it.
We'll need to set up IaC and scripts for those like I have for them in https://github.com/gctools-outilsgc/Kubernetes-config/tree/master/prod/collab

**Comment by LecCory** [comment]
I'm having a hard time finding the storage account where the scripts live that are being called from k8s via curl 

http://collab.gccollab.svc.cluster.local/cron/daily and http://collab.gccollab.svc.cluster.local/cron/weekly

I just want to have a look at them to see if we can simply dump them into a function app.

**Comment by Phanoix** [comment]
Those are part of elgg, https://learn.elgg.org/en/2.3/admin/cron.html

**Comment by LecCory** [comment]
Oh, in that case this should be no problem for a function app trigger to make an http req to the daily and weekly. I'll start working on them in Cypher

**Comment by LecCory** [comment]
Recreated the daily and weekly cron jobs as triggered function apps. Simply sends a GET request to the {siteURL}/cron/daily and weekly. The response is logged in app insights. 

https://portal.azure.com/#@devgcx.ca/resource/subscriptions/4655aaed-2bd9-49c6-a9a2-60b57c27cce2/resourceGroups/rg-gctools-managedServices-dev/providers/Microsoft.Web/sites/dgcx-collab-cron/functionsList

**Comment by LecCory** [comment]
Moving back to in progress as I realized I hard coded the site url. Will switch to an env variable for reusability.

**Comment by LecCory** [comment]
SITEURL replaced the hardcoded URL, the only portion that remains is /cron/{daily|weekly} also removed some debug configs I left in from my tests.

**Comment by LecCory** [comment]
Jobs are up in Cypher will add a function app to the existing bicep deployment and a task in the pipeline to deploy the functions

**Comment by LecCory** [comment]
Will open a new task for the addition of the function app to the infra deployment
