### ISSUE TITLE
Plan out the frontend application routing

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/Issues#28]

**Comment by doug0102** [comment]
**Public Routes**
- register (reroutes to GCaccount)
- login (reroutes to GCaccount)
- terms
- splash
- about
- privacy
- stats
- help (reroutes to support.gccollab.ca) 

**Private Routes**
- home
- search
- newsfeed
- thewire
- groups
- members
- missions (career)
- blog
- dashboard
- profile
- settings
- messages
- friends
- bookmarks
- invite
- event_calendar
