### ISSUE TITLE
Angular - Research splitting i18n translations for each component / lazy loaded module

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/Issues#34]
Currently all translations sit in a single file for each language. This file and all its translations are loaded as soon as the app starts or when the language changes. This isn't ideal as it will be harder to maintain as the app grows, and not all translations are needed since the majority of our modules are lazy loaded.

Research into if we can split this into multiple files that can be loaded as needed at the module level, or even better, at the component level.

**Comment by doug0102** [comment]
@piet0024 @Phanoix @vid 

I got this working in my branch but I'm not sure I'm going to go ahead with using it yet. It actually added a bit more complexity than I initially thought and the performance impact of loading one big json file vs smaller ones on demand is pretty negligible. I think it may make more sense to leave it all loading from one main file so it makes the developer experience a bit smoother.

To load individual translations lazy loaded you need to import the TranslateModule using the forChild method into the lazy loaded module, then create a separate HTTPLoader that points to a specific file path of your choice. State between different TranslateModules can be shared or isolated with the isolate flag, but then you would need to create a tracker that updates and synchs state for all other TranslateModules... The developers would need to remember to keep using this pattern throughout the app and if any components were to move around then it would create a headache of copy/pasting translations from old files into new ones. Overall it just adds more complexity to the app and may not be worth it.

Longs story short it's possible but may be something we can do later when the project is more mature and we know things aren't going to change too much.

**Comment by vid** [comment]
Sounds like a too early optimization to me, so I say do it later.
