### ISSUE TITLE
Azure testing result dashboard + landing page for repo

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/Issues#44]
Generate a dashboard page that can be used as a widget on the Azure devops project page.

**Comment by vid** [comment]
Dashboard publishing feature is under development. https://github.com/withhaibun/haibun/tree/feature/adding-dashboard

**Comment by vid** [comment]
* updated review publishing to include multiple executions and handle folder based paths (previously it was flattening paths to support expiry, this is now an option)
* created a web-component based dashboard page
* updated publishing methods
* added new actions to publish dashboard, and dashboard links

Currently testing in target azure environment.
