### ISSUE TITLE
Research and test moving storage account to storage account

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/Issues#50]

**Comment by Phanoix** [comment]
This is specifically using `azcopy copy` command, works well but does induce considerable latency as expected so should only be done during very off-peak hours for anything that prod might depend on if copying a significant amount of files.
~10GB in 10k+ files took 2 minutes to transfer, it scales up and down the number of concurrent connections as it goes so it would probably be faster than 200 minutes to transfer 1TB of similar files.

**Comment by Phanoix** [comment]
https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-files?source=recommendations#copy-files-between-storage-accounts

tl;dr:
copy from source_share in mysourceaccount to destinations_share in mydestinationaccount
`azcopy copy 'https://mysourceaccount.file.core.windows.net/source_share?sv=...' 'https://mydestinationaccount.file.core.windows.net/destinations_share?sv=...'`
