### ISSUE TITLE
GCCollab - Managed Services - Copy Collab data files

### ISSUE THREAD

**Issue by LecCory** [gctools-outilsgc/Issues#58]
We need to determine if we want to copy the current collab files (~1TB) into the Cypher data storage location, or do we want to leave the instance in Cypher running with some basic dev data and instead copy that 1TB of data into what will be the production instance of Collab managed service on the current production tenant. 

If the current prod data is already in an Azure fileshare, could we get away with simply adding it as a mounted file path in the web app and then avoid having to copy anything over?

~~Depends on gctools-outilsgc/Issues#56~~

**Comment by LecCory** [comment]
We'll need to plan for a date and time after hours to start the copy. We have a long weekend coming up (Canada day Saturday following Monday off) that could buy us 1 extra day of low impact site usage if we need it.

**Comment by Phanoix** [comment]
While I don't expect it to take long enough for that to be necessary, considering the significant latency impact on the whole storage account it might still be a good idea to pick an extra quiet weekend like that since it's right around the corner anyways.

**Comment by LecCory** [comment]
Copy task finished Monday evening
